/* ============
 * Mutation types for the account module
 * ============
 *
 * The mutation types that are available
 * on the auth module.
 */

export const MERGE_NIM_SESSIONS = 'MERGE_NIM_SESSIONS';
export const MERGE_NIM_SESSION_MSGS = 'MERGE_NIM_SESSION_MSGS';
export const MERGE_NIM_USERS = 'MERGE_NIM_USERS';
export const MERGE_NIM_TEAMS = 'MERGE_NIM_TEAMS';
export const CUT_NIM_TEAM_MEMBERS = 'CUT_NIM_TEAM_MEMBERS';
export const MERGE_NIM_TEAM_MEMBERS = 'MERGE_NIM_TEAM_MEMBERS';
export const DELETE_NIM_SESSION = 'DELETE_NIM_SESSION';
export const GET_NIM_SUPPORT_DB_STATUS = 'GET_NIM_SUPPORT_DB_STATUS';
export const SET_SESSION_SYNC_MSG_DONE = 'SET_SESSION_SYNC_MSG_DONE';
export const SWITCH_NIM_CURRENT_SESSION = 'SWITCH_NIM_CURRENT_SESSION';
export const DELETE_NIM_TEAM = 'DELETE_NIM_TEAM';
export const UPDATE_NIM_TEAM_INFO = 'UPDATE_NIM_TEAM_INFO';
export const UPDATE_NIM_TEAM_USER_INFO = 'UPDATE_NIM_TEAM_USER_INFO';
export const SET_SESSION_SYNC_TEAMMEMBERS_DONE = 'SET_SESSION_SYNC_TEAMMEMBERS_DONE';

export default {
  MERGE_NIM_SESSIONS,
  MERGE_NIM_SESSION_MSGS,
  MERGE_NIM_USERS,
  MERGE_NIM_TEAMS,
  CUT_NIM_TEAM_MEMBERS,
  MERGE_NIM_TEAM_MEMBERS,
  DELETE_NIM_SESSION,
  GET_NIM_SUPPORT_DB_STATUS,
  SET_SESSION_SYNC_MSG_DONE,
  SWITCH_NIM_CURRENT_SESSION,
  DELETE_NIM_TEAM,
  UPDATE_NIM_TEAM_INFO,
  UPDATE_NIM_TEAM_USER_INFO,
  SET_SESSION_SYNC_TEAMMEMBERS_DONE,
};
